apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  namespace: ddni
  labels:
    app: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: ai-agent:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent-service
  namespace: ddni
spec:
  selector:
    app: ai-agent
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: LoadBalancer
  externalIPs: [10.36.88.165]


